services:
    engine:
        build:
            context: ./engine
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - '3333:3333'
        volumes:
            - ./engine:/app
            - /app/node_modules
        env_file: ./engine/.env
        depends_on:
            - database
        networks:
            - iboto-network

    database:
        image: mysql:8.0
        container_name: iboto-database
        restart: unless-stopped
        env_file:
            - ./database.env
        volumes:
            - database-data:/var/lib/mysql
        ports:
            - '3307:3307'
        networks:
            - iboto-network

    database-admin:
        image: adminer
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - database
        networks:
            - iboto-network

networks:
    iboto-network:
        driver: bridge

volumes:
    database-data:
