services:
    engine:
        container_name: iboto-engine
        build:
            context: ./engine
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file: ./engine/.env
        stdin_open: true
        tty: true
        ports:
            - "3333:3333"
        volumes:
            - /app/node_modules
        depends_on:
            - database
        networks:
            - network

    database:
        container_name: iboto-database
        image: mysql:8.0
        restart: unless-stopped
        env_file:
            - ./database.env
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - database-data:/var/lib/mysql
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    database-data:
