import { Candidate } from '@/type'

export const candidates: Candidate[] = [
    {
        name: 'ABALOS, BENHUR',
        party: 'PFP',
        code: 'ABALOSBENHUR2025',
        placement: 1,
    },
    {
        name: 'ADONIS, JEROME',
        party: 'MKBYN',
        code: 'ADONISJEROME2025',
        placement: 2,
    },
    {
        name: 'AMAD, WILSON',
        party: 'IND',
        code: 'AMADWILSON2025',
        placement: 3,
    },
    {
        name: 'ANDAMO, NARS ALYN',
        party: 'MKBYN',
        code: 'ANDAMONARSALYN2025',
        placement: 4,
    },
    {
        name: 'AQUINO, BAM',
        party: 'KNP',
        code: 'AQUINOBAM2025',
        placement: 5,
    },
    {
        name: 'ARAMBULO, RONNEL',
        party: 'MKBYN',
        code: 'ARAMBULORONNEL2025',
        placement: 6,
    },
    {
        name: 'ARELLANO, ERNESTO',
        party: 'KTPNAN',
        code: 'ARELLANOERNESTO2025',
        placement: 7,
    },
    {
        name: 'BALLON, ROBERTO',
        party: 'IND',
        code: 'BALLONROBERTO2025',
        placement: 8,
    },
    {
        name: 'BINAY, ABBY',
        party: 'NPC',
        code: 'BINAYABBY2025',
        placement: 9,
    },
    {
        name: 'BONDOC, JIMMY',
        party: 'PDPLBN',
        code: 'BONDOCJIMMY2025',
        placement: 10,
    },
    {
        name: 'BORJA REVILLA, RAMON, JR.',
        party: 'LAKAS',
        code: 'BORJAREVILLARAMONJR2025',
        placement: 11,
    },
    {
        name: 'BOSITA, COLONEL',
        party: 'IND',
        code: 'BOSITACOLONEL2025',
        placement: 12,
    },
    {
        name: 'BROSAS, ARLENE',
        party: 'MKBYN',
        code: 'BROSASARLENE2025',
        placement: 13,
    },
    {
        name: 'CABONEGRO, ROY',
        party: 'DPP',
        code: 'CABONEGROROY2025',
        placement: 14,
    },
    {
        name: 'CAPUYAN, ALLEN',
        party: 'PPP',
        code: 'CAPUYANALLEN2025',
        placement: 15,
    },
    {
        name: 'CASIÑO, TEDDY',
        party: 'MKBYN',
        code: 'CASINOTEDDY2025',
        placement: 16,
    },
    {
        name: 'CASTRO, TEACHER FRANCE',
        party: 'MKBYN',
        code: 'CASTROTEACHERFRANCE2025',
        placement: 17,
    },
    {
        name: 'CAYETANO, PIA',
        party: 'NP',
        code: 'CAYETANOPIA2025',
        placement: 18,
    },
    {
        name: "D'ANGELO, DAVID",
        party: 'BUMYOG',
        code: 'DANGELODAVID2025',
        placement: 19,
    },
    {
        name: 'DE ALBAN, ATTORNEY ANGELO',
        party: 'IND',
        code: 'DEALBANATTORNEYANGELO2025',
        placement: 20,
    },
    {
        name: 'DE GUZMAN, KA LEODY',
        party: 'PLM',
        code: 'DEGUZMANKALEODY2025',
        placement: 21,
    },
    {
        name: 'DELA ROSA, BATO',
        party: 'PDPLBN',
        code: 'DELAROSABATO2025',
        placement: 22,
    },
    {
        name: 'DOMINGO, NANAY MIMI',
        party: 'MKBYN',
        code: 'DOMINGONANAYMIMI2025',
        placement: 23,
    },
    {
        name: 'ESCOBAL, ARNEL',
        party: 'PM',
        code: 'ESCOBALARNEL2025',
        placement: 24,
    },
    {
        name: 'ESPIRITU, LUKE',
        party: 'PLM',
        code: 'ESPIRITULUKE2025',
        placement: 25,
    },
    {
        name: 'FLORANDA, MODY PISTON',
        party: 'MKBYN',
        code: 'FLORANDAMODYPISTON2025',
        placement: 26,
    },
    {
        name: 'GAMBOA, MARC LOUIE',
        party: 'IND',
        code: 'GAMBOAMARCLOUIE2025',
        placement: 27,
    },
    {
        name: 'GO, BONG GO',
        party: 'PDPLBN',
        code: 'GOBONGG2025',
        placement: 28,
    },
    {
        name: 'GONZALES, NORBERTO',
        party: 'PDP',
        code: 'GONZALESNORBERTO2025',
        placement: 29,
    },
    {
        name: 'HINLO, JAYVEE',
        party: 'PDPLBN',
        code: 'HINLOJAYVEE2025',
        placement: 30,
    },
    {
        name: 'HONASAN, GRINGO',
        party: 'RP',
        code: 'HONASANGRINGO2025',
        placement: 31,
    },
    {
        name: 'JOSE, RELLY JR.',
        party: 'KBL',
        code: 'JOSERELLYJR2025',
        placement: 32,
    },
    {
        name: 'LACSON, PING',
        party: 'IND',
        code: 'LACSONPING2025',
        placement: 33,
    },
    {
        name: 'LAMBINO, RAUL',
        party: 'NP',
        code: 'LAMBINORAUL2025',
        placement: 34,
    },
    {
        name: 'LAPID, LITO',
        party: 'NPC',
        code: 'LAPIDLITO2025',
        placement: 35,
    },
    {
        name: 'LEE, MANOY WILBERT',
        party: 'AKSYON',
        code: 'LEEMANOYWILBERT2025',
        placement: 36,
    },
    {
        name: 'LIDASAN, AMIRAH',
        party: 'MKBYN',
        code: 'LIDASANAMIRAH2025',
        placement: 37,
    },
    {
        name: 'MARCOLETA, RODANTE',
        party: 'IND',
        code: 'MARCOLETARODANTE2025',
        placement: 38,
    },
    {
        name: 'MARCOS, IMEE R.',
        party: 'NP',
        code: 'MARCOSIMEER2025',
        placement: 39,
    },
    {
        name: 'MARQUEZ, NORMAN',
        party: 'IND',
        code: 'MARQUEZNORMAN2025',
        placement: 40,
    },
    {
        name: 'MARTINEZ, ERIC',
        party: 'IND',
        code: 'MARTINEZERIC2025',
        placement: 41,
    },
    {
        name: 'MATA, DOC MARITES',
        party: 'IND',
        code: 'MATADOCMARITES2025',
        placement: 42,
    },
    {
        name: 'MATULA, ATTY. SONNY',
        party: 'WPP',
        code: 'MATULAATTYSONNY2025',
        placement: 43,
    },
    {
        name: 'MAZA, LIZA',
        party: 'MKBYN',
        code: 'MAZALIZA2025',
        placement: 44,
    },
    {
        name: 'MENDOZA, HEIDI',
        party: 'IND',
        code: 'MENDOZAHEIDI2025',
        placement: 45,
    },
    {
        name: 'MONTEMAYOR, JOEY',
        party: 'IND',
        code: 'MONTEMAYORJOEY2025',
        placement: 46,
    },
    {
        name: 'MUSTAPHA, SUBAIR',
        party: 'WPP',
        code: 'MUSTAPHASUBAIR2025',
        placement: 47,
    },
    {
        name: 'OLIVAR, JOSE JESSIE',
        party: 'IND',
        code: 'OLIVARJOSEJESSIE2025',
        placement: 48,
    },
    {
        name: 'ONG, DOC WILLIE',
        party: 'AKSYON',
        code: 'ONGDOCWILLIE2025',
        placement: 49,
    },
    {
        name: 'PACQUIAO, MANNY PACMAN',
        party: 'PFP',
        code: 'PACQUIAOMANNYPACMAN2025',
        placement: 50,
    },
    {
        name: 'PANGILINAN, KIKO',
        party: 'LP',
        code: 'PANGILINANKIKO2025',
        placement: 51,
    },
    {
        name: 'QUERUBIN, ARIEL PORFIRIO',
        party: 'NP',
        code: 'QUERUBINARIELPORFIRIO2025',
        placement: 52,
    },
    {
        name: 'QUIBOLOY, APOLLO',
        party: 'IND',
        code: 'QUIBOLOYAPOLLO2025',
        placement: 53,
    },
    {
        name: 'RAMOS, DANILO',
        party: 'MKBYN',
        code: 'RAMOSDANILO2025',
        placement: 54,
    },
    {
        name: 'REVILLAME, WILLIE WIL',
        party: 'IND',
        code: 'REVILLAMEWILLIEWIL2025',
        placement: 55,
    },
    {
        name: 'RODRIGUEZ, ATTY. VIC',
        party: 'IND',
        code: 'RODRIGUEZATTYVIC2025',
        placement: 56,
    },
    {
        name: 'SAHIDULLA, NUR-ANA',
        party: 'IND',
        code: 'SAHIDULLANURANA2025',
        placement: 57,
    },
    {
        name: 'SALVADOR, PHILLIP IPE',
        party: 'PDPLBN',
        code: 'SALVADORPHILLIPIPE2025',
        placement: 58,
    },
    {
        name: 'SOTTO, TITO',
        party: 'NPC',
        code: 'SOTTOTITO2025',
        placement: 59,
    },
    {
        name: 'TAPADO, MICHAEL BONGBONG',
        party: 'PM',
        code: 'TAPADOMICHAELBONGBONG2025',
        placement: 60,
    },
    {
        name: 'TOLENTINO, FRANCIS TOL',
        party: 'PFP',
        code: 'TOLENTINOFRANCISTOL2025',
        placement: 61,
    },
    {
        name: 'TULFO, BEN BITAG',
        party: 'IND',
        code: 'TULFOBENBITAG2025',
        placement: 62,
    },
    {
        name: 'TULFO, ERWIN',
        party: 'LAKAS',
        code: 'TULFOERWIN2025',
        placement: 63,
    },
    {
        name: 'VALBUENA, MAR MANIBELA',
        party: 'IND',
        code: 'VALBUENAMARMANIBELA2025',
        placement: 64,
    },
    {
        name: 'VERCELES, LEANDRO',
        party: 'IND',
        code: 'VERCELESLEANDRO2025',
        placement: 65,
    },
    {
        name: 'VILLAR, CAMILLE',
        party: 'NP',
        code: 'VILLARCAMILLE2025',
        placement: 66,
    },
]
