import { Candidate } from '@/type';

export const candidates: Candidate[] = [
    {
        id: 1,
        name: 'ABALOS, BENHUR',
        party: 'PFP',
        image_url: '/placeholder.png',
    },
    {
        id: 2,
        name: 'ADONIS, JEROME',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 3,
        name: 'AMAD, WILSON',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 4,
        name: 'ANDAMO, NARS ALYN',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 5,
        name: 'AQUINO, BAM',
        party: 'KNP',
        image_url: '/placeholder.png',
    },
    {
        id: 6,
        name: 'ARAMBULO, RONNEL',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 7,
        name: 'ARELLANO, ERNESTO',
        party: 'KTPNAN',
        image_url: '/placeholder.png',
    },
    {
        id: 8,
        name: 'BALLON, ROBERTO',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 9,
        name: 'BINAY, ABBY',
        party: 'NPC',
        image_url: '/placeholder.png',
    },
    {
        id: 10,
        name: 'BONDOC, JIMMY',
        party: 'PDPLBN',
        image_url: '/placeholder.png',
    },
    {
        id: 11,
        name: 'BORJA REVILLA, RAMON, JR.',
        party: 'LAKAS',
        image_url: '/placeholder.png',
    },
    {
        id: 12,
        name: 'BOSITA, COLONEL',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 13,
        name: 'BROSAS, ARLENE',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 14,
        name: 'CABONEGRO, ROY',
        party: 'DPP',
        image_url: '/placeholder.png',
    },
    {
        id: 15,
        name: 'CAPUYAN, ALLEN',
        party: 'PPP',
        image_url: '/placeholder.png',
    },
    {
        id: 16,
        name: 'CASIÑO, TEDDY',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 17,
        name: 'CASTRO, TEACHER FRANCE',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 18,
        name: 'CAYETANO, PIA',
        party: 'NP',
        image_url: '/placeholder.png',
    },
    {
        id: 19,
        name: "D'ANGELO, DAVID",
        party: 'BUMYOG',
        image_url: '/placeholder.png',
    },
    {
        id: 20,
        name: 'DE ALBAN, ATTORNEY ANGELO',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 21,
        name: 'DE GUZMAN, KA LEODY',
        party: 'PLM',
        image_url: '/placeholder.png',
    },
    {
        id: 22,
        name: 'DELA ROSA, BATO',
        party: 'PDPLBN',
        image_url: '/placeholder.png',
    },
    {
        id: 23,
        name: 'DOMINGO, NANAY MIMI',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 24,
        name: 'ESCOBAL, ARNEL',
        party: 'PM',
        image_url: '/placeholder.png',
    },
    {
        id: 25,
        name: 'ESPIRITU, LUKE',
        party: 'PLM',
        image_url: '/placeholder.png',
    },
    {
        id: 26,
        name: 'FLORANDA, MODY PISTON',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 27,
        name: 'GAMBOA, MARC LOUIE',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 28,
        name: 'GO, BONG GO',
        party: 'PDPLBN',
        image_url: '/placeholder.png',
    },
    {
        id: 29,
        name: 'GONZALES, NORBERTO',
        party: 'PDP',
        image_url: '/placeholder.png',
    },
    {
        id: 30,
        name: 'HINLO, JAYVEE',
        party: 'PDPLBN',
        image_url: '/placeholder.png',
    },
    {
        id: 31,
        name: 'HONASAN, GRINGO',
        party: 'RP',
        image_url: '/placeholder.png',
    },
    {
        id: 32,
        name: 'JOSE, RELLY JR.',
        party: 'KBL',
        image_url: '/placeholder.png',
    },
    {
        id: 33,
        name: 'LACSON, PING',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 34,
        name: 'LAMBINO, RAUL',
        party: 'NP',
        image_url: '/placeholder.png',
    },
    {
        id: 35,
        name: 'LAPID, LITO',
        party: 'NPC',
        image_url: '/placeholder.png',
    },
    {
        id: 36,
        name: 'LEE, MANOY WILBERT',
        party: 'AKSYON',
        image_url: '/placeholder.png',
    },
    {
        id: 37,
        name: 'LIDASAN, AMIRAH',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 38,
        name: 'MARCOLETA, RODANTE',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 39,
        name: 'MARCOS, IMEE R.',
        party: 'NP',
        image_url: '/placeholder.png',
    },
    {
        id: 40,
        name: 'MARQUEZ, NORMAN',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 41,
        name: 'MARTINEZ, ERIC',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 42,
        name: 'MATA, DOC MARITES',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 43,
        name: 'MATULA, ATTY. SONNY',
        party: 'WPP',
        image_url: '/placeholder.png',
    },
    {
        id: 44,
        name: 'MAZA, LIZA',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 45,
        name: 'MENDOZA, HEIDI',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 46,
        name: 'MONTEMAYOR, JOEY',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 47,
        name: 'MUSTAPHA, SUBAIR',
        party: 'WPP',
        image_url: '/placeholder.png',
    },
    {
        id: 48,
        name: 'OLIVAR, JOSE JESSIE',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 49,
        name: 'ONG, DOC WILLIE',
        party: 'AKSYON',
        image_url: '/placeholder.png',
    },
    {
        id: 50,
        name: 'PACQUIAO, MANNY PACMAN',
        party: 'PFP',
        image_url: '/placeholder.png',
    },
    {
        id: 51,
        name: 'PANGILINAN, KIKO',
        party: 'LP',
        image_url: '/placeholder.png',
    },
    {
        id: 52,
        name: 'QUERUBIN, ARIEL PORFIRIO',
        party: 'NP',
        image_url: '/placeholder.png',
    },
    {
        id: 53,
        name: 'QUIBOLOY, APOLLO',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 54,
        name: 'RAMOS, DANILO',
        party: 'MKBYN',
        image_url: '/placeholder.png',
    },
    {
        id: 55,
        name: 'REVILLAME, WILLIE WIL',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 56,
        name: 'RODRIGUEZ, ATTY. VIC',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 57,
        name: 'SAHIDULLA, NUR-ANA',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 58,
        name: 'SALVADOR, PHILLIP IPE',
        party: 'PDPLBN',
        image_url: '/placeholder.png',
    },
    {
        id: 59,
        name: 'SOTTO, TITO',
        party: 'NPC',
        image_url: '/placeholder.png',
    },
    {
        id: 60,
        name: 'TAPADO, MICHAEL BONGBONG',
        party: 'PM',
        image_url: '/placeholder.png',
    },
    {
        id: 61,
        name: 'TOLENTINO, FRANCIS TOL',
        party: 'PFP',
        image_url: '/placeholder.png',
    },
    {
        id: 62,
        name: 'TULFO, BEN BITAG',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 63,
        name: 'TULFO, ERWIN',
        party: 'LAKAS',
        image_url: '/placeholder.png',
    },
    {
        id: 64,
        name: 'VALBUENA, MAR MANIBELA',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 65,
        name: 'VERCELES, LEANDRO',
        party: 'IND',
        image_url: '/placeholder.png',
    },
    {
        id: 66,
        name: 'VILLAR, CAMILLE',
        party: 'NP',
        image_url: '/placeholder.png',
    },
];
